on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
    - run: docker build -t ${{ secrets.username }}/webpages:v1 .
    - run: docker push ${{ secrets.username }}/webpages:v1
